### ISSUE TITLE
Remove auto ac option

### ISSUE THREAD

**Issue by mb200k** [nVuln/homebridge-lg-thinq#149]
Is it possible to remove the auto ac option? I dont like the separate tile as i never use it, and if i keep on same tile homekit thinks its two devices and i cant just click to turn on, have to open the tile. If possible please add a setting to make permanent auto or disable auto tile like the fan setting. Thanks

**Comment by timwnl** [comment]
In another LG Thinq plug-in the 'auto' option was added to the regular temperature control. So you could select 'auto, cooling, heating' etc. It is possible to set a range in where the Auto option should function. for example between 19 and 22 degrees. 

Maybe there is a good reason why it has been added as a separate switch, but I would prefer a more 'clean' interface too.

**Comment by mb200k** [comment]
> > In another LG Thinq plug-in the 'auto' option was added to the regular temperature control. So you could select 'auto, cooling, heating' etc. It is possible to set a range in where the Auto option should function. for example between 19 and 22 degrees.
> 
> Auto mode in LG AC not working like this, only single target temperature could be selected, not range
> 
> @mb200k I'll add plugin setting to enable/disable this button on next release

Many thanks for the awesome plugin!!

**Comment by nVuln** [comment]
> > > In another LG Thinq plug-in the 'auto' option was added to the regular temperature control. So you could select 'auto, cooling, heating' etc. It is possible to set a range in where the Auto option should function. for example between 19 and 22 degrees.
> > 
> > 
> > Auto mode in LG AC not working like this, only single target temperature could be selected, not range
> > @mb200k I'll add plugin setting to enable/disable this button on next release
> 
> Many thanks for the awesome plugin!!

I already published test version `v1.2.15-test.5`, please install and try it, set `ac_auto_mode_button = false` to disable it

> Another question. I do have a multi unit airco and I have the 'fan' and 'dry' options in my LG app. Is that something that can be enabled in your solution?

currently this plugin do not support Fan & Dry mode, if you want to implement it, please turn on homebridge debug mode, turn on/off dry & fan mode 1-2 times, then collect some debug logging and upload it, I'll try add a button to control (plz open another issue for easier tracking 😃 )

**Comment by mb200k** [comment]
> > > > In another LG Thinq plug-in the 'auto' option was added to the regular temperature control. So you could select 'auto, cooling, heating' etc. It is possible to set a range in where the Auto option should function. for example between 19 and 22 degrees.
> > > 
> > > 
> > > Auto mode in LG AC not working like this, only single target temperature could be selected, not range
> > > @mb200k I'll add plugin setting to enable/disable this button on next release
> > 
> > 
> > Many thanks for the awesome plugin!!
> 
> I already published test version `v1.2.15-test.5`, please install and try it, set `ac_auto_mode_button = false` to disable it
> 
> > Another question. I do have a multi unit airco and I have the 'fan' and 'dry' options in my LG app. Is that something that can be enabled in your solution?
> 
> currently this plugin do not support Fan & Dry mode, if you want to implement it, please turn on homebridge debug mode, turn on/off dry & fan mode 1-2 times, then collect some debug logging and upload it, I'll try add a button to control (plz open another issue for easier tracking 😃 )

I disabled the auto button on settings but it shows up on homekit, already deleted child bridge and re added and still persists, maybe the auto button can be moved to the heat/cool/off setting instead?

**Comment by nVuln** [comment]
> I disabled the auto button on settings but it shows up on homekit, already deleted child bridge and re added and still persists, 

try clean cached accessories

> maybe the auto button can be moved to the heat/cool/off setting instead?

no

**Comment by mb200k** [comment]
I tried to clean cache, remove pairing , it does not show as auto button anymore but it shows as jet mode

**Comment by K0ciq** [comment]
Hello, I have just updated to 1.2.15 version but I do not see the option to disable AC Auto Mode button in Homebridge. Could you guys please navigate me on how to disable this for Homebridge/HomeKit? Thanks in advance!

**Comment by VoltIcaRus** [comment]
![화면 캡처 2022-06-14 154741](https://user-images.githubusercontent.com/3735740/173511413-68a01123-4ac1-4cce-bb05-5188ec3d2de0.png)
From v1.2.16
I configured it like this, but still
The auto mode switch and air clean switch are displayed.
Is there any way to disable it?

**Comment by nVuln** [comment]
> ![화면 캡처 2022-06-14 154741](https://user-images.githubusercontent.com/3735740/173511413-68a01123-4ac1-4cce-bb05-5188ec3d2de0.png) From v1.2.16 I configured it like this, but still The auto mode switch and air clean switch are displayed. Is there any way to disable it?

please clean all cached accessory in homebridge setting page

**Comment by VoltIcaRus** [comment]
@nVuln Oh I didn't know it existed
Thank you so much it has been fixed.
