### ISSUE TITLE
Temperature not updating Without opening the ThinQ APP

### ISSUE THREAD

**Issue by Maverick5269-lab** [nVuln/homebridge-lg-thinq#278]
Hi all, 

I've found that my ACs LG did not update the temperature sensors.
If I open the LG ThinQ on the phone it will update automatically on both and in HomeBridge. 

This is happening in all AC models? 

Thanks
Best Regards

**Comment by nVuln** [comment]
I fixed this issue on `v1.7.0`, please update

**Comment by Maverick5269-lab** [comment]
Thanks, works perfect

**Comment by romanarenas** [comment]
Hi guys,
I was experiencing the same issue and it still happens after updating to the latest version (v1.8.1). 
Did you do something extra to fix it?

Thanks
Roman

**Comment by nVuln** [comment]
@romanarenas is your AC using thinq 1 or thinq 2?

**Comment by romanarenas** [comment]
I have the "Enable ThinQ1 support enabled" however I think the ac is  thinq2 since I see this log message: "Start MQTT listener for thinq2 device". Is there a better way to confirm it?

**Comment by nVuln** [comment]
@romanarenas turn on homebridge debug mode and collect some debug logging at startup

**Comment by Maverick5269-lab** [comment]
Hi,

This problem reappeared. 
The temperature cannot be updated unless I enter the LG thinQ App. 
Tried versions 1.7.0, 1.8.0 same issue.

Thanks
