### ISSUE TITLE
Plugin problem with Hoobs

### ISSUE THREAD

**Issue by nickbolero** [nVuln/homebridge-lg-thinq#81]
Hi I'm testing this plugin on Hoobs. I entered the correct credentials. But it doesn't work. I am attaching the log. Can you help me?
[LGThinQ] Unknown Error: Error: Request failed with status code 406
at createError (/home/hoobs/.hoobs/node_modules/axios/lib/core/createError.js:16:15)
at settle (/home/hoobs/.hoobs/node_modules/axios/lib/core/settle.js:17:12)
at IncomingMessage.handleStreamEnd (/home/hoobs/.hoobs/node_modules/axios/lib/adapters/http.js:269:11)
at IncomingMessage.emit (events.js:215:7)
at endReadableNT (_stream_readable.js:1184:12)
at processTicksAndRejections (internal/process/task_queues.js:80:21) {
config: {
url: 'https://it.emp.lgsmartplatform.com/emp/v2.0/account/session/xxxxxxxxx8905%40gmail.com',
method: 'post',
data: 'user_auth2=9dhCLHO3cgE6a7IunbAxRNGVx%2B%2BGcdZG%2F6tDsufwpK9hIH%2BCoCfCpAjrcEjPPLnVZtPLIrLx0UYL1rPT02NPRy7aQpZGHndBAnt7FZ8uUFxOdc9WZ5ACUJdatdKM7aIFBqMea2Qsg%2BFO8mo1yDFIxh0pUFycuGPu58L9jp9sqRR%2Bc9ARsHsZaDiFTodNDDhM&password_hash_prameter_flag=Y&svc_list=SVC202%2CSVC710',
headers: {
Accept: 'application/json',
'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8',
'X-Application-Key': '6V1V8H2BN5P9ZQGOI5DAQ92YZBDO3EK9',
'X-Client-App-Key': 'LGAO221A02',
'X-Lge-Svccode': 'SVC709',
'X-Device-Type': 'M01',
'X-Device-Platform': 'ADR',
'X-Device-Language-Type': 'IETF',
'X-Device-Publish-Flag': 'Y',
'X-Device-Country': 'IT',
'X-Device-Language': 'it-IT',
'X-Signature': 'GCr5jRgfS3rbBId0UbO3sjukUgfdI9iZFCct5L0Fdis=',
'X-Timestamp': '1631694284',
'Access-Control-Allow-Origin': '*',
'Accept-Encoding': 'gzip, deflate, br',
'Accept-Language': 'en-US,en;q=0.9',
'User-Agent': 'axios/0.21.4',
'Content-Length': 270
},
transformRequest: [ [Function: transformRequest] ],
transformResponse: [ [Function: transformResponse] ],
timeout: 0,
adapter: [Function: httpAdapter],
xsrfCookieName: 'XSRF-TOKEN',
xsrfHeaderName: 'X-XSRF-TOKEN',
maxContentLength: -1,
maxBodyLength: -1,
validateStatus: [Function: validateStatus],
transitional: {
silentJSONParsing: true,
forcedJSONParsing: true,
clarifyTimeoutError: false
}
},
request: ClientRequest {
_events: [Object: null prototype] {
socket: [Function],
abort: [Function],
aborted: [Function],
connect: [Function],
error: [Function],
timeout: [Function],
prefinish: [Function: requestOnPrefinish]
},
_eventsCount: 7,
_maxListeners: undefined,
outputData: [],
outputSize: 0,
writable: true,
_last: true,
chunkedEncoding: false,
shouldKeepAlive: false,
useChunkedEncodingByDefault: true,
sendDate: false,
_removedConnection: false,
_removedContLen: false,
_removedTE: false,
_contentLength: null,
_hasBody: true,
_trailer: '',
finished: true,
_headerSent: true,
socket: TLSSocket {
_tlsOptions: [Object],
_secureEstablished: true,
_securePending: false,
_newSessionPending: false,
_controlReleased: true,
_SNICallback: null,
servername: 'it.emp.lgsmartplatform.com',
alpnProtocol: false,
authorized: true,
authorizationError: null,
encrypted: true,
_events: [Object: null prototype],
_eventsCount: 9,
connecting: false,
_hadError: false,
_parent: null,
_host: 'it.emp.lgsmartplatform.com',
_readableState: [ReadableState],
readable: true,
_maxListeners: undefined,
_writableState: [WritableState],
writable: false,
allowHalfOpen: false,
_sockname: null,
_pendingData: null,
_pendingEncoding: '',
server: undefined,
_server: null,
ssl: [TLSWrap],
_requestCert: true,
_rejectUnauthorized: true,
parser: null,
_httpMessage: [Circular],
[Symbol(res)]: [TLSWrap],
[Symbol(asyncId)]: 881,
[Symbol(kHandle)]: [TLSWrap],
[Symbol(lastWriteQueueSize)]: 0,
[Symbol(timeout)]: null,
[Symbol(kBuffer)]: null,
[Symbol(kBufferCb)]: null,
[Symbol(kBufferGen)]: null,
[Symbol(kBytesRead)]: 0,
[Symbol(kBytesWritten)]: 0,
[Symbol(connect-options)]: [Object]
},
connection: TLSSocket {
_tlsOptions: [Object],
_secureEstablished: true,
_securePending: false,
_newSessionPending: false,
_controlReleased: true,
_SNICallback: null,
servername: 'it.emp.lgsmartplatform.com',
alpnProtocol: false,
authorized: true,
authorizationError: null,
encrypted: true,
_events: [Object: null prototype],
_eventsCount: 9,
connecting: false,
_hadError: false,
_parent: null,
_host: 'it.emp.lgsmartplatform.com',
_readableState: [ReadableState],
readable: true,
_maxListeners: undefined,
_writableState: [WritableState],
writable: false,
allowHalfOpen: false,
_sockname: null,
_pendingData: null,
_pendingEncoding: '',
server: undefined,
_server: null,
ssl: [TLSWrap],
_requestCert: true,
_rejectUnauthorized: true,
parser: null,
_httpMessage: [Circular],
[Symbol(res)]: [TLSWrap],
[Symbol(asyncId)]: 881,
[Symbol(kHandle)]: [TLSWrap],
[Symbol(lastWriteQueueSize)]: 0,
[Symbol(timeout)]: null,
[Symbol(kBuffer)]: null,
[Symbol(kBufferCb)]: null,
[Symbol(kBufferGen)]: null,
[Symbol(kBytesRead)]: 0,
[Symbol(kBytesWritten)]: 0,
[Symbol(connect-options)]: [Object]
},
_header: 'POST /emp/v2.0/account/session/xxxxxxxxxxx8905%40gmail.com HTTP/1.1\r\n' +
'Accept: application/json\r\n' +
'Content-Type: application/x-www-form-urlencoded;charset=UTF-8\r\n' +
'X-Application-Key: 6V1V8H2BN5P9ZQGOI5DAQ92YZBDO3EK9\r\n' +
'X-Client-App-Key: LGAO221A02\r\n' +
'X-Lge-Svccode: SVC709\r\n' +
'X-Device-Type: M01\r\n' +
'X-Device-Platform: ADR\r\n' +
'X-Device-Language-Type: IETF\r\n' +
'X-Device-Publish-Flag: Y\r\n' +
'X-Device-Country: IT\r\n' +
'X-Device-Language: it-IT\r\n' +
'X-Signature: GCr5jRgfS3rbBId0UbO3sjukUgfdI9iZFCct5L0Fdis=\r\n' +
'X-Timestamp: 1631694284\r\n' +
'Access-Control-Allow-Origin: \r\n' +
'Accept-Encoding: gzip, deflate, br\r\n' +
'Accept-Language: en-US,en;q=0.9\r\n' +
'User-Agent: axios/0.21.4\r\n' +
'Content-Length: 270\r\n' +
'Host: it.emp.lgsmartplatform.com\r\n' +
'Connection: close\r\n' +
'\r\n',
_onPendingData: [Function: noopPendingOutput],
agent: Agent {
_events: [Object: null prototype],
_eventsCount: 1,
_maxListeners: undefined,
defaultPort: 443,
protocol: 'https:',
options: [Object],
requests: {},
sockets: [Object],
freeSockets: {},
keepAliveMsecs: 1000,
keepAlive: false,
maxSockets: Infinity,
maxFreeSockets: 256,
maxCachedSessions: 100,
_sessionCache: [Object]
},
socketPath: undefined,
method: 'POST',
path: '/emp/v2.0/account/session/xxxxxxxxxx8905%40gmail.com',
_ended: true,
res: IncomingMessage {
_readableState: [ReadableState],
readable: false,
_events: [Object: null prototype],
_eventsCount: 3,
_maxListeners: undefined,
socket: [TLSSocket],
connection: [TLSSocket],
httpVersionMajor: 1,
httpVersionMinor: 1,
httpVersion: '1.1',
complete: true,
headers: [Object],
rawHeaders: [Array],
trailers: {},
rawTrailers: [],
aborted: false,
upgrade: false,
url: '',
method: null,
statusCode: 406,
statusMessage: '406',
client: [TLSSocket],
_consuming: false,
_dumped: false,
req: [Circular],
responseUrl: 'https://it.emp.lgsmartplatform.com/emp/v2.0/account/session/xxxxxxxxxxxxx8905%40gmail.com',
redirects: []
},
aborted: false,
timeoutCb: null,
upgradeOrConnect: false,
parser: null,
maxHeadersCount: null,
_redirectable: Writable {
_writableState: [WritableState],
writable: true,
_events: [Object: null prototype],
_eventsCount: 2,
_maxListeners: undefined,
_options: [Object],
_ended: true,
_ending: true,
_redirectCount: 0,
_redirects: [],
_requestBodyLength: 270,
_requestBodyBuffers: [],
_onNativeResponse: [Function],
_currentRequest: [Circular],
_currentUrl: 'https://it.emp.lgsmartplatform.com/emp/v2.0/account/session/xxxxxxxxxxxxxx8905%40gmail.com'
},
[Symbol(kNeedDrain)]: false,
[Symbol(isCorked)]: false,
[Symbol(kOutHeaders)]: [Object: null prototype] {
accept: [Array],
'content-type': [Array],
'x-application-key': [Array],
'x-client-app-key': [Array],
'x-lge-svccode': [Array],
'x-device-type': [Array],
'x-device-platform': [Array],
'x-device-language-type': [Array],
'x-device-publish-flag': [Array],
'x-device-country': [Array],
'x-device-language': [Array],
'x-signature': [Array],
'x-timestamp': [Array],
'access-control-allow-origin': [Array],
'accept-encoding': [Array],
'accept-language': [Array],
'user-agent': [Array],
'content-length': [Array],
host: [Array]
}
},
response: {
status: 406,
statusText: '406',
headers: {
'access-control-allow-headers': 'Origin, Access-Control-Allow-Origin, X-Device-Language-Type, X-Lge-System-Id, X-Application-Key, X-Device-Country, X-Device-Language, X-Device-Platform, X-Platform-Code, X-Platform-Version, X-Device-Publish-Flag, X-Device-Type, X-Lge-Svccode, X-Signature, X-Timestamp, X-Login-Session, Content-Type, Accept, X-Device-Id, X-Client-App-Key, X-Device-Model, X-Device-SDK-VERSION, X-Device-FCK, X-Device-Country-Group, X-Device-Netcast-Platform-Version, X-Device-FW-Version, X-Device-Locale, X-Device-Remote-Flag, X-Authentication, X-Device-Product, X-Device-Sales-Model, X-Device-Eco-Info, X-Device-Personalization',
'access-control-allow-methods': 'OPTIONS,POST,PUT,GET,DELETE',
'access-control-allow-origin': '',
'content-type': 'application/json;charset=UTF-8',
date: 'Wed, 15 Sep 2021 08:24:46 GMT',
server: 'Apache',
'set-cookie': [Array],
'x-server-time': 'Wed, 15 Sep 2021 08:24:46 GMT',
'content-length': '189',
connection: 'Close'
},
config: {
url: 'https://it.emp.lgsmartplatform.com/emp/v2.0/account/session/xxxxxxxxxxxxx8905%40gmail.com',
method: 'post',
data: 'user_auth2=9dhCLHO3cgE6a7IunbAxRNGVx%2B%2BGcdZG%2F6tDsufwpK9hIH%2BCoCfCpAjrcEjPPLnVZtPLIrLx0UYL1rPT02NPRy7aQpZGHndBAnt7FZ8uUFxOdc9WZ5ACUJdatdKM7aIFBqMea2Qsg%2BFO8mo1yDFIxh0pUFycuGPu58L9jp9sqRR%2Bc9ARsHsZaDiFTodNDDhM&password_hash_prameter_flag=Y&svc_list=SVC202%2CSVC710',
headers: [Object],
transformRequest: [Array],
transformResponse: [Array],
timeout: 0,
adapter: [Function: httpAdapter],
xsrfCookieName: 'XSRF-TOKEN',
xsrfHeaderName: 'X-XSRF-TOKEN',
maxContentLength: -1,
maxBodyLength: -1,
validateStatus: [Function: validateStatus],
transitional: [Object]
},
request: ClientRequest {
_events: [Object: null prototype],
_eventsCount: 7,
_maxListeners: undefined,
outputData: [],
outputSize: 0,
writable: true,
_last: true,
chunkedEncoding: false,
shouldKeepAlive: false,
useChunkedEncodingByDefault: true,
sendDate: false,
_removedConnection: false,
_removedContLen: false,
_removedTE: false,
_contentLength: null,
_hasBody: true,
_trailer: '',
finished: true,
_headerSent: true,
socket: [TLSSocket],
connection: [TLSSocket],
_header: 'POST /emp/v2.0/account/session/xxxxxxxxxxxx8905%40gmail.com HTTP/1.1\r\n' +
'Accept: application/json\r\n' +
'Content-Type: application/x-www-form-urlencoded;charset=UTF-8\r\n' +
'X-Application-Key: 6V1V8H2BN5P9ZQGOI5DAQ92YZBDO3EK9\r\n' +
'X-Client-App-Key: LGAO221A02\r\n' +
'X-Lge-Svccode: SVC709\r\n' +
'X-Device-Type: M01\r\n' +
'X-Device-Platform: ADR\r\n' +
'X-Device-Language-Type: IETF\r\n' +
'X-Device-Publish-Flag: Y\r\n' +
'X-Device-Country: IT\r\n' +
'X-Device-Language: it-IT\r\n' +
'X-Signature: GCr5jRgfS3rbBId0UbO3sjukUgfdI9iZFCct5L0Fdis=\r\n' +
'X-Timestamp: 1631694284\r\n' +
'Access-Control-Allow-Origin: *\r\n' +
'Accept-Encoding: gzip, deflate, br\r\n' +
'Accept-Language: en-US,en;q=0.9\r\n' +
'User-Agent: axios/0.21.4\r\n' +
'Content-Length: 270\r\n' +
'Host: it.emp.lgsmartplatform.com\r\n' +
'Connection: close\r\n' +
'\r\n',
_onPendingData: [Function: noopPendingOutput],
agent: [Agent],
socketPath: undefined,
method: 'POST',
path: '/emp/v2.0/account/session/xxxxxxxxxxxx8905%40gmail.com',
_ended: true,
res: [IncomingMessage],
aborted: false,
timeoutCb: null,
upgradeOrConnect: false,
parser: null,
maxHeadersCount: null,
_redirectable: [Writable],
[Symbol(kNeedDrain)]: false,
[Symbol(isCorked)]: false,
[Symbol(kOutHeaders)]: [Object: null prototype]
},
data: { error: [Object] }
},
isAxiosError: true,
toJSON: [Function: toJSON]
}
15/9/2021, 10:24:47 [LGThinQ] ThinQ API is not ready. please check configuration and try again.

**Comment by nVuln** [comment]
did your account used 3rd-party login (like Google, Apple ID) ?

**Comment by nickbolero** [comment]
Yes! Apple ID

**Comment by nVuln** [comment]
> Yes! Apple ID? I can not do anything?

sorry for late reply, I'm a litte busy today, please update to `v1.2.4`, I fixed some login bug in this version

if you using Hoobs, I recommend you should create new LG account (not logged by 3rd-party provider) and migrate all device to new account, it's faster

Another way, you can login by visit this URL: [click here to login](https://us.m.lgaccount.com/spx/login/signIn?country=IT&language=en-IT&client_id=LGAO221A02&svc_list=SVC202&svc_integrated=Y&redirect_uri=https%3A%2F%2Fit.m.lgaccount.com%2Flogin%2FiabClose&show_thirdparty_login=LGE%2CMYLG%2CGGL%2CAMZ%2CFBK%2CAPPL&division=ha&callback_url=https%3A%2F%2Fit.m.lgaccount.com%2Flogin%2FiabClose&oauth2State=12345&show_select_country=N) and select login by Apple ID
when logged successfully, you may redirected to blank page (may be error page page not found), don't worry, just copy that URL and you can find refresh_token in this URL, it will look like `https://us.m.lgaccount.com/spx/login/iabClose?access_token=*******&refresh_token=***this is what you need***&oauth2_backend_url=https://us.lgeapi.com/`
then you put refresh token to plugin setting, change Auth Mode to token also

**Comment by nickbolero** [comment]
> > Yes! Apple ID? I can not do anything?
> 
> sorry for late reply, I'm a litte busy today, please update to `v1.2.4`, I fixed some login bug in this version
> 
> if you using Hoobs, I recommend you should create new LG account (not logged by 3rd-party provider) and migrate all device to new account, it's faster
> 
> Another way, you can login by visit this URL: [click here to login](https://us.m.lgaccount.com/spx/login/signIn?country=IT&language=en-IT&client_id=LGAO221A02&svc_list=SVC202&svc_integrated=Y&redirect_uri=https%3A%2F%2Fit.m.lgaccount.com%2Flogin%2FiabClose&show_thirdparty_login=LGE%2CMYLG%2CGGL%2CAMZ%2CFBK%2CAPPL&division=ha&callback_url=https%3A%2F%2Fit.m.lgaccount.com%2Flogin%2FiabClose&oauth2State=12345&show_select_country=N) and select login by Apple ID
> when logged successfully, you may redirected to blank page (may be error page page not found), don't worry, just copy that URL and you can find refresh_token in this URL, it will look like `https://us.m.lgaccount.com/spx/login/iabClose?access_token=*******&refresh_token=***this is what you need***&oauth2_backend_url=https://us.lgeapi.com/`
> then you put refresh token to plugin setting, change Auth Mode to token also

Thanks for the reply. before trying another account, i would like to try the token method. I have only two problems from the hoobs interface still cannot find the version update to 1.2.4.
then in the link what should I use as a token?
https://us.m.lgaccount.com/spx/login/signIn?callback_url=https%3A%2F%2Fit.m.lgaccount.com%2Flogin%2FiabClose&client_id=LGAO221A02&country=IT&division=ha&language=en-IT&redirect_uri=https%3A%2F%2Fit.m.lgaccount.com%2Flogin%2FiabClose&show_select_country=N&show_thirdparty_login=LGE%2CMYLG%2CGGL%2CAMZ%2CFBK%2CAPPL&svc_list=SVC202&svc_integrated=Y&user_thirdparty_token=eyJraWQiOiJZdXlYb1kiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwcGxlaWQuYXBwbGUuY29tIiwiYXVkIjoiY29tLmxnYWNjb3VudC5hcHBsZWlkIiwiZXhwIjoxNjMxNzg3Mjg5LCJpYXQiOjE2MzE3MDA4ODksInN1YiI6IjAwMDI2MC4yMzA5OWZhNzUwNzA0Yjg2YjYyYWU4OGY3NjcyYTdlMy4xNzM4Iiwibm9uY2UiOiJzcHgyMSIsImNfaGFzaCI6InZYYVliaXBwWjRpSEMxR1FocVd4M2ciLCJlbWFpbCI6Imdpb3Zhbm5pLnZpdGllbGxvODkwNUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6InRydWUiLCJhdXRoX3RpbWUiOjE2MzE3MDA4ODksIm5vbmNlX3N1cHBvcnRlZCI6dHJ1ZX0.TAhmxMV0JNLweJDUY52O8JxJ9bnHfT0jngClB9LGiHrGPu4TZjgGKb9AbaWQeA9LF-nRHXnFj9u9uLLtJt08ZiG5-ndsP7jSj8X6nAXlJkJTN2YEKQotuYbFD7_b6cYbuUaMEw6XqxgWpIi8Qf4W-iWJJ2rmFo_E-pSVln899QP2eq0saKcFg4jzhQW-EReFwnGTz2aFFRSJnajkEEe8_8zaYTEFLl0SvU1XA_8WBtHwn9zCGHsi-6vbFLN1XaJx7I-_S7kNXSEW94lnpBWz-uCR2VK0WAJXhdIcBCebsSqTkbiyILD6F0YBBHpB--KHetnqlWHePQb3k4Mm7Pq9Dg&user_id=000260.23099fa750704b86b62ae88f7672a7e3.1738&user_id_type=APPL

**Comment by nVuln** [comment]
> > > Yes! Apple ID? I can not do anything?
> > 
> > 
> > sorry for late reply, I'm a litte busy today, please update to `v1.2.4`, I fixed some login bug in this version
> > if you using Hoobs, I recommend you should create new LG account (not logged by 3rd-party provider) and migrate all device to new account, it's faster
> > Another way, you can login by visit this URL: [click here to login](https://us.m.lgaccount.com/spx/login/signIn?country=IT&language=en-IT&client_id=LGAO221A02&svc_list=SVC202&svc_integrated=Y&redirect_uri=https%3A%2F%2Fit.m.lgaccount.com%2Flogin%2FiabClose&show_thirdparty_login=LGE%2CMYLG%2CGGL%2CAMZ%2CFBK%2CAPPL&division=ha&callback_url=https%3A%2F%2Fit.m.lgaccount.com%2Flogin%2FiabClose&oauth2State=12345&show_select_country=N) and select login by Apple ID
> > when logged successfully, you may redirected to blank page (may be error page page not found), don't worry, just copy that URL and you can find refresh_token in this URL, it will look like `https://us.m.lgaccount.com/spx/login/iabClose?access_token=*******&refresh_token=***this is what you need***&oauth2_backend_url=https://us.lgeapi.com/`
> > then you put refresh token to plugin setting, change Auth Mode to token also
> 
> Thanks for the reply. before trying another account, i would like to try the token method. I have only two problems from the hoobs interface still cannot find the version update to 1.2.4.
> then in the link what should I use as a token?
> ** hidden **

nop, look like this method is not worked now, LG changed something on their server

**Comment by nVuln** [comment]
> > > Yes! Apple ID? I can not do anything?
> > 
> > 
> > sorry for late reply, I'm a litte busy today, please update to `v1.2.4`, I fixed some login bug in this version
> > if you using Hoobs, I recommend you should create new LG account (not logged by 3rd-party provider) and migrate all device to new account, it's faster
> > Another way, you can login by visit this URL: [click here to login](https://us.m.lgaccount.com/spx/login/signIn?country=IT&language=en-IT&client_id=LGAO221A02&svc_list=SVC202&svc_integrated=Y&redirect_uri=https%3A%2F%2Fit.m.lgaccount.com%2Flogin%2FiabClose&show_thirdparty_login=LGE%2CMYLG%2CGGL%2CAMZ%2CFBK%2CAPPL&division=ha&callback_url=https%3A%2F%2Fit.m.lgaccount.com%2Flogin%2FiabClose&oauth2State=12345&show_select_country=N) and select login by Apple ID
> > when logged successfully, you may redirected to blank page (may be error page page not found), don't worry, just copy that URL and you can find refresh_token in this URL, it will look like `https://us.m.lgaccount.com/spx/login/iabClose?access_token=*******&refresh_token=***this is what you need***&oauth2_backend_url=https://us.lgeapi.com/`
> > then you put refresh token to plugin setting, change Auth Mode to token also
> 
> Thanks for the reply. before trying another account, i would like to try the token method. I have only two problems from the hoobs interface still cannot find the version update to 1.2.4.
> then in the link what should I use as a token?
> ** hidden **

maybe hoobs server not synced latest version, if you allowed, I can try obtain `refresh_token` from your provided url and send it to private email

**Comment by nickbolero** [comment]
> nop, look like this method is not worked now, LG changed something on their server

So you propose to update the plugin and try with an accout that does not pass for apple id?

**Comment by nVuln** [comment]
> > nop, look like this method is not worked now, LG changed something on their server
> 
> So you propose to update the plugin and try with an accout that does not pass for apple id?

yup, you can try it in `v1.2.3`, this version still worked in some country
but if you got any error, please update to `v1.2.4` and try again
I don't know when hoobs server synchronize latest version

sorry I can't help for 3rdparty login in Hoobs

**Comment by nickbolero** [comment]
if you can I would be grateful

**Comment by nVuln** [comment]
> if you can I would be grateful
> […](#)
> Il giorno 15 set 2021, alle ore 13:32, nVuln ***@***.***> ha scritto: ﻿ Yes! Apple ID? I can not do anything? sorry for late reply, I'm a litte busy today, please update to v1.2.4, I fixed some login bug in this version if you using Hoobs, I recommend you should create new LG account (not logged by 3rd-party provider) and migrate all device to new account, it's faster Another way, you can login by visit this URL: click here to login and select login by Apple ID when logged successfully, you may redirected to blank page (may be error page page not found), don't worry, just copy that URL and you can find refresh_token in this URL, it will look like https://us.m.lgaccount.com/spx/login/iabClose?access_token=*******&refresh_token=***this is what you need***&oauth2_backend_url=https://us.lgeapi.com/ then you put refresh token to plugin setting, change Auth Mode to token also Thanks for the reply. before trying another account, i would like to try the token method. I have only two problems from the hoobs interface still cannot find the version update to 1.2.4. then in the link what should I use as a token? ** hidden ** maybe hoobs server not synced latest version, if you allowed, I can try obtain refresh_token from your provided url and send it to private email — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

please give me your email address, I'll send it

**Comment by nickbolero** [comment]
> > if you can I would be grateful
> 
> please give me your email address, I'll send it

nickbolero@hotmail.it

**Comment by nVuln** [comment]
> > > if you can I would be grateful
> > 
> > 
> > please give me your email address, I'll send it
> 
> ** hidden email **

already sent, please check

**Comment by nickbolero** [comment]
> > > > if you can I would be grateful
> > > 
> > > 
> > > please give me your email address, I'll send it
> > 
> > 
> > ** hidden email **
> 
> already sent, please check
I saw. I'm checking if it works. Thanks I'll let you know

**Comment by nickbolero** [comment]
Hi, then after putting the token you sent. The plugin works, but it no longer made me acquire data from other plugins. Therefore I uninstalled it. But still I see the entity on Apple home. I have to try if the new version doesn't give me any problems. But I have to wait for hoobs to update its servers. now how do i delete the two entities on apple home. Then I wanted to ask you can you have only the two functions that I see on lg? I attach photos.
![01775fc9-975b-473b-8b3e-f75e550f2cb9](https://user-images.githubusercontent.com/54214273/133453280-ac2b179c-6e26-4c93-9cb9-93c0d7a58d69.JPG)

**Comment by nVuln** [comment]
> now how do i delete the two entities on apple home. 

you need clean cached accessories, this is Hoobs problem, not my plugin

> Then I wanted to ask you can you have only the two functions that I see on lg? I attach photos.

currently, plugin will display both fridge and freezer temperature, but look like you have Fridge only, I'll fix this in next release
about Express Mode, you need enable it in config, [more detail here](https://github.com/nVuln/homebridge-lg-thinq/wiki/Device-Configuration#refrigerator)

**Comment by nickbolero** [comment]
> you need clean cached accessories, this is Hoobs problem, not my plugin
could you tell me how to clean hoobs cache?




> currently, plugin will display both fridge and freezer temperature, but look like you have Fridge only, I'll fix this in next release
> about Express Mode, you need enable it in config, [more detail here](https://github.com/nVuln/homebridge-lg-thinq/wiki/Device-Configuration#refrigerator)
I will wait for your next version. Yes, I can confirm that I can only see and control the temperature of the refrigerator. And I can enable Express Mode

**Comment by nVuln** [comment]
> > you need clean cached accessories, this is Hoobs problem, not my plugin
> 
> could you tell me how to clean hoobs cache?
> 
> > currently, plugin will display both fridge and freezer temperature, but look like you have Fridge only, I'll fix this in next release
> > about Express Mode, you need enable it in config, [more detail here](https://github.com/nVuln/homebridge-lg-thinq/wiki/Device-Configuration#refrigerator)
> 
> I will wait for your next version. Yes, I can confirm that I can only see and control the temperature of the refrigerator. And I can enable Express Mode

* From the HOOBS UI, click on top right menu and select Terminal
* In the terminal type: sudo rm -rf accessories then press enter.
* In the terminal type: sudo rm -rf persist then press enter.
* Click the restart homebridge icon in the top right menu. All the accessories will be deleted and must be reset up in Homekit.

**Comment by nickbolero** [comment]
hi, I wanted to let you know that I have tried the plugin update. And I can see the status and send the refrigerator controls. I just have a problem with the logs for the plugin: [https://github.com/norberttech/homebridge-ch-ac](url) I use for air conditioners. Can you help me?
Thank you for all the help you have given me so far.
I attach log:
[log.txt](https://github.com/nVuln/homebridge-lg-thinq/files/7185719/log.txt)

**Comment by nVuln** [comment]
> hi, I wanted to let you know that I have tried the plugin update. And I can see the status and send the refrigerator controls. I just have a problem with the logs for the plugin: [https://github.com/norberttech/homebridge-ch-ac](url) I use for air conditioners. Can you help me?
> Thank you for all the help you have given me so far.
> I attach log:
> [log.txt](https://github.com/nVuln/homebridge-lg-thinq/files/7185719/log.txt)

you should contact plugin's developer to get better support
sorry I can't help
